apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: service-mesh-installation
  namespace: istio-system
spec:
  version: v1.1

  threeScale:
    enabled: false

  gateways:
    egress:
      autoscaleEnabled: false
    ingress:
      autoscaleEnabled: false
    additionalEgress:
      ui-egressgateway:
        enabled: true
        runtime:
          deployment:
            autoScaling:
              enabled: false
            replicas: 1
          container:
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                cpu: 100m
                memory: 200Mi
          pod:
            metadata:
             labels:
               app: ui-egressgateway
        service: {}
    additionalIngress:
      ui-ingressgateway:
        enabled: true
        routerMode: standard
        runtime:
          deployment:
            autoScaling:
              enabled: false
            replicas: 1
          container:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 500Mi
          pod:
            metadata:
             labels:
               app: ui-ingressgateway
        service:
          type: LoadBalancer
      http-ingressgateway:
        enabled: true
        routerMode: standard
        runtime:
          deployment:
            autoScaling:
              enabled: false
            replicas: 1
          container:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 500Mi
          pod:
            metadata:
             labels:
               app: http-ingressgateway
        service:
          type: LoadBalancer
  istio:
    global:
      mtls:
        enabled: false
        auto: false
      disablePolicyChecks: false
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi

    mixer:
      policy:
        autoscaleEnabled: false

      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0

    kiali:
      dashboard:
        user: admin
        passphrase: redhat
    tracing:
      enabled: true


